# Generated by Django 4.1.5 on 2023-03-08 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('btsweb', '0003_btsuser_anotheraddress_btsuser_city_btsuser_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='btsuser',
            name='password',
        ),
    ]
